// Level icon images for player tags on the map (shown inside nickname tag)
export const LEVEL_ICON_URLS: Record<number, string> = {
    1: '/Gui/IMG_Player_Level_/ur1.webp',
    2: '/Gui/IMG_Player_Level_/ur2.webp',
    3: '/Gui/IMG_Player_Level_/ur3.webp',
    4: '/Gui/IMG_Player_Level_/ur4.webp',
    5: '/Gui/IMG_Player_Level_/ur5.webp',
    6: '/Gui/IMG_Player_Level_/ur6.webp',
    7: '/Gui/IMG_Player_Level_/ur7.webp',
    8: '/Gui/IMG_Player_Level_/ur8.webp',
    9: '/Gui/IMG_Player_Level_/ur9.webp',
    10: '/Gui/IMG_Player_Level_/ur10.webp',
    11: '/Gui/IMG_Player_Level_/ur11.webp',
    12: '/Gui/IMG_Player_Level_/ur12.webp',
    13: '/Gui/IMG_Player_Level_/ur13.webp',
    14: '/Gui/IMG_Player_Level_/ur14.webp',
    15: '/Gui/IMG_Player_Level_/ur15.webp',
    16: '/Gui/IMG_Player_Level_/ur15.webp',
    17: '/Gui/IMG_Player_Level_/ur15.webp',
    18: '/Gui/IMG_Player_Level_/ur15.webp',
    19: '/Gui/IMG_Player_Level_/ur15.webp',
    20: '/Gui/IMG_Player_Level_/ur15.webp',
    21: '/Gui/IMG_Player_Level_/ur15.webp',
    22: '/Gui/IMG_Player_Level_/ur15.webp',
    23: '/Gui/IMG_Player_Level_/ur15.webp',
    24: '/Gui/IMG_Player_Level_/ur15.webp',
    25: '/Gui/IMG_Player_Level_/ur15.webp',
    26: '/Gui/IMG_Player_Level_/ur15.webp',
    27: '/Gui/IMG_Player_Level_/ur15.webp',
    28: '/Gui/IMG_Player_Level_/ur15.webp',
    29: '/Gui/IMG_Player_Level_/ur15.webp',
    30: '/Gui/IMG_Player_Level_/ur15.webp'
};

// Player avatar shown below nickname on map (different for each level)
export const PLAYER_AVATAR_URLS: Record<number, string> = {
    1: '/Gui/Avatar_Player_Level_/ut-K4z-uu-Bjg-1.webp',
    2: '/Gui/Avatar_Player_Level_/i-E3j3-y-YS78-1.webp',
    3: '/Gui/Avatar_Player_Level_/23cy-Wxc-Vbu-Y-1.webp',
    4: '/Gui/Avatar_Player_Level_/4.webp',
    5: '/Gui/Avatar_Player_Level_/5.webp',
    6: '/Gui/Avatar_Player_Level_/6.webp',
    7: '/Gui/Avatar_Player_Level_/7.webp',
    8: '/Gui/Avatar_Player_Level_/8.webp',
    9: '/Gui/Avatar_Player_Level_/9-2.webp',
    10: '/Gui/Avatar_Player_Level_/10-2.webp',
    11: '/Gui/Avatar_Player_Level_/11.webp',
    12: '/Gui/Avatar_Player_Level_/12.webp',
    13: '/Gui/Avatar_Player_Level_/13.webp',
    14: '/Gui/Avatar_Player_Level_/14.webp',
    15: '/Gui/Avatar_Player_Level_/15.webp',
    16: '/Gui/Avatar_Player_Level_/15.webp',
    17: '/Gui/Avatar_Player_Level_/15.webp',
    18: '/Gui/Avatar_Player_Level_/15.webp',
    19: '/Gui/Avatar_Player_Level_/15.webp',
    20: '/Gui/Avatar_Player_Level_/15.webp',
    21: '/Gui/Avatar_Player_Level_/15.webp',
    22: '/Gui/Avatar_Player_Level_/15.webp',
    23: '/Gui/Avatar_Player_Level_/15.webp',
    24: '/Gui/Avatar_Player_Level_/15.webp',
    25: '/Gui/Avatar_Player_Level_/15.webp',
    26: '/Gui/Avatar_Player_Level_/15.webp',
    27: '/Gui/Avatar_Player_Level_/15.webp',
    28: '/Gui/Avatar_Player_Level_/15.webp',
    29: '/Gui/Avatar_Player_Level_/15.webp',
    30: '/Gui/Avatar_Player_Level_/15.webp'
};
